name: All Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: All Tests

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'tem'
        cache: maven
    - name: Build with Maven
      run: ./mvnw verify
    - name: Check clean git state
      run: ./.github/workflows/check-clean-git-state.sh
