name: Update Contributors

on:
#  schedule: # Run workflow automatically
#    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  main:
    runs-on: ubuntu-latest
    name: Update Contributors

    steps:
      - uses: minicli/action-contributors@v3.3
        name: "Update a projects CONTRIBUTORS file"
        env:
          CONTRIB_REPOSITORY: 'McPringle/komunumo'
          CONTRIB_OUTPUT_FILE: 'CONTRIBUTORS.md'
          CONTRIB_IGNORE: 'dependabot[bot],github-actions[bot],renovate[bot],renovate-bot'
      - name: Commit changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: 'CONTRIBUTORS.md'
          commit-msg: ':busts_in_silhouette: Update contributors'
          github-token: ${{ secrets.GITHUB_TOKEN }}
